---
- name: Provision MMOInsweeper Server
  hosts: all
  become: yes
  vars_files:
    - vault.yml
  vars:
    ansible_ssh_private_key_file: "~/.ssh/id_ed25519"
    domain_name: "mmoinsweeper.top"

  tasks:
    - name: Create mmoinsweeper user
      user:
        name: mmoinsweeper
        state: present
        groups: sudo
        shell: /bin/bash

    - name: Set up authorized keys for mmoinsweeper user
      authorized_key:
        user: mmoinsweeper
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

    - name: Ensure sudo group has passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Install Certbot and Nginx plugin
      apt:
        name:
          - certbot
          - python3-certbot-nginx
        state: present

    - name: Create Certbot webroot directory
      file:
        path: /var/www/certbot
        state: directory
        mode: '0755'

    - name: Configure Nginx reverse proxy
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/{{ domain_name }}
      notify: Reload Nginx

    - name: Enable Nginx site
      file:
        src: /etc/nginx/sites-available/{{ domain_name }}
        dest: /etc/nginx/sites-enabled/{{ domain_name }}
        state: link
      notify: Reload Nginx

    - name: Obtain SSL certificate
      command: certbot --nginx -d {{ domain_name }} --non-interactive --agree-tos --email {{ certbot_email }} --redirect
      args:
        creates: /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem

    - name: Create directory for static content
      file:
        path: /var/www/{{ domain_name }}
        state: directory
        owner: mmoinsweeper
        group: mmoinsweeper
        mode: '0755'

    - name: Copy static content
      copy:
        src: static/
        dest: /var/www/{{ domain_name }}
        owner: mmoinsweeper
        group: mmoinsweeper
        mode: '0644'

    - name: Copy game binary
      copy:
        src: mmoinsweeper
        dest: /usr/local/bin/mmoinsweeper
        owner: root
        group: root
        mode: '0755'

    - name: Create systemd service file
      template:
        src: mmoinsweeper.service.j2
        dest: /etc/systemd/system/mmoinsweeper.service
      notify: Reload systemd

    - name: Start and enable mmoinsweeper service
      systemd:
        name: mmoinsweeper
        state: started
        enabled: yes

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded

    - name: Reload systemd
      systemd:
        daemon_reload: yes
